- hosts: MPI
  vars:
    NODE_VERSION: 20.5.1
  tasks:
    - name: install deps
      become: true
      apt:
        state: present
        pkg:
          - curl
          - jq
          - tmux
          - make
          - llvm
          - g++
          - clang
          - gcc
            # for gnuplot w/o x11
          - gnuplot-nox
            # for pdfunite
          - poppler-utils
            # for converting intel-att (for supercop)
          - nasm
          - cmake
            # mount ntfs
          - nfs-common
          # autotools for measuresuite / assemblyline
          - autoconf
          - pkg-config
          - libtool

    - name: setup nvm
      ansible.builtin.shell:
        cmd: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      args:
        executable: /bin/bash
    
    - name: install Node/NPM {{NODE_VERSION}}
      ansible.builtin.shell:
        cmd: source ~/.nvm/nvm.sh && nvm install {{NODE_VERSION}}
      args:
        executable: /bin/bash
  
    - name: install libassemblyline
      git:
        repo: 'https://github.com/MQuaresma/AssemblyLine.git'
        dest: "~/AssemblyLine"
        version: "main"
        update: yes
        force: yes

    - name: autogen
      command:
        chdir: "~/AssemblyLine"
        cmd: bash autogen.sh

    - name: configure
      command:
        chdir: "~/AssemblyLine"
        cmd: ./configure

    - name: make all
      make:
        target: all
        chdir: "~/AssemblyLine"

    # - name: make install
    #   become: true
    #   make:
    #     target: install
    #     chdir: "~/AssemblyLine"

    - name: make install
      become: true
      command:
        chdir: "/home/miguel/AssemblyLine"
        cmd: make install

    - name: ldconfig
      become: true
      command:
        cmd: ldconfig
    
    - name: install measuresuite
      git:
        repo: 'https://github.com/MQuaresma/MeasureSuite.git'
        dest: "~/MeasureSuite"
        version: "main"
        update: yes
        force: yes
    
    - name: install ts
      ansible.builtin.shell:
        chdir: "~/MeasureSuite/ts"
        cmd: source ~/.nvm/nvm.sh && npm install
      args:
        executable: /bin/bash

    - name: build measuresuite
      ansible.builtin.shell:
        chdir: "~/MeasureSuite"
        cmd: source ~/.nvm/nvm.sh && npm run build
      args:
        executable: /bin/bash