# vim: set tw=2 sw=2 sts=2:

- hosts: intel amd
  vars: 
    asmlineversion: "1.3.1"
  tasks:
    - name: install deps
      become: true
      apt:
        state: present
        pkg:
          - curl
          - jq
          - tmux
          - make
          - llvm
            # for gnuplot w/o x11
          - gnuplot-nox
            # for pdfunite
          - poppler-utils
            # for converting intel-att (for supercop)
          - nasm
          - cmake
            # mount ntfs
          - nfs-common
          # autotools for measuresuite / assemblyline
          - autoconf
          - pkg-config
    - name: install libassemblyline
      unarchive:
        src: "https://github.com/0xADE1A1DE/AssemblyLine/releases/download/v{{ asmlineversion }}/assemblyline-{{ asmlineversion }}.tar.gz"
        dest: /tmp
        remote_src: yes

    - name: configure
      command:
        chdir: "/tmp/assemblyline-{{ asmlineversion }}"
        cmd: ./configure

    - name: make all
      make:
        target: all
        chdir: "/tmp/assemblyline-{{ asmlineversion }}"

    - name: make install
      become: true
      make:
        target: install
        chdir: "/tmp/assemblyline-{{ asmlineversion }}"

    - name: ldconfig
      become: true
      command:
        cmd: ldconfig
