#!/usr/bin/env ansible-playbook
# vim: set tw=2 sw=2 sts=2:


- hosts: intel amd
  become: false
  gather_facts: false
  tasks:
    - name: Update git repo
      git:
        repo: 'https://github.com/0xADE1A1DE/CryptOpt.git'
        dest: ~/cryptopt
        version: "main"
        update: yes
        force: yes

    - name: build
      make:
        target: all
        chdir: ~/cryptopt





