#!/usr/bin/env ansible-playbook
# vim: set tw=2 sw=2 sts=2:


- hosts: intel amd
  become: false
  gather_facts: false
  tasks:
    - name: RESET FREQ
      when: yes
      #dont use become, it'll change ~
      command:
        cmd: sudo ./set_frequency.sh default
        chdir: ~/cryptopt/modules/scripts/misc
      ignore_errors: yes
    - name: Update git repo
      git:
        repo: 'https://github.com/0xADE1A1DE/CryptOpt.git'
        dest: ~/cryptopt
        version: "main"
        version: "feature/bls12"
        update: yes
        force: yes

    - name: deepclean
      when: yes
      make:
        target: deepclean
        chdir: ~/cryptopt

    - name: build
      make:
        target: all
        chdir: ~/cryptopt


