#!/usr/bin/env ansible-playbook
# vim: set tw=2 sw=2 sts=2:


- hosts: intel amd
  vars:
    CC: clang
    runArgs:
      # example running from fiat
      - "--bridge fiat"
      - "--curve curve25519"
      - "--method mul"

      # example running manual
      # - "--bridge manual"
      # - "--cFile ./test/manual-bridge/dettman/secp256k1_dettman_64.c"
      # - "--jsonFile ./test/manual-bridge/dettman/secp256k1_dettman_64.json"

      # example running from bitcoincore
      # - "--bridge bitcoin-core"
      # - "--curve secp256k1"
      # - "--method square"

      - "--evals 200k"
      - "--bets 20"
      - "--betRatio 0.1"
      # - "--no-proof"
      - "--resultDir ~/cryptopt/results.wilson.{{ansible_date_time.iso8601_basic_short}}"

  tasks:
    - name: ensure session.mux is up to date
      template:
        src: ./templates/session.mux.j2
        dest: ~/session.mux
        mode: '0744'

    - name: Look for the "tmux" process
      shell: ps -ef | grep tmux | grep -v grep
      ignore_errors: yes
      register: process_list
      changed_when: false

    - name: Start "tmux" if needed
      command: tmux new-session -d
      when: "process_list.stdout.find('tmux') == -1"

    - name: Will start the tmux optimiser based on current ./session.mux
      command: bash ~/session.mux cryptopt
      async: 2592000               # 60*60*24*30 – 1 month
      poll: 0
