#!/usr/bin/env ansible-playbook
# vim: set tw=2 sw=2 sts=2:


- hosts: intel amd
  vars:
    CC: clang
    # apparently ansible resolves each of those everytime it launches a run, which results in some reuslts being in ~00 and some in ~01, one second apart.
    # I'm trying here to blank out seconds. thereby this only occurs once a minute, not once per second...
    date: "{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}T{{ansible_date_time.hour}}{{ansible_date_time.minute}}00"
    runArgs:
      # example running from fiat
      - "--bridge fiat"
      - "--curve secp256k1_dettman"
      - "--method square"

      # example running manual
      # - "--bridge manual"
      # - "--cFile ./test/manual-bridge/dettman/secp256k1_dettman_64.c"
      # - "--jsonFile ./test/manual-bridge/dettman/secp256k1_dettman_64.json"

      # example running from bitcoincore
      # - "--bridge bitcoin-core"
      # - "--curve secp256k1"
      # - "--method square"

      - "--evals 400k"
      - "--bets 30"
      - "--betRatio 0.1"
      - "--resultDir ~/cryptopt/results.400k.30.{{date}}"

  tasks:
    - name: ensure session.mux is up to date
      template:
        src: ./templates/session.mux.j2
        dest: ~/session.mux
        mode: '0744'

    - name: Look for the "tmux" process
      shell: ps -ef | grep tmux | grep -v grep
      ignore_errors: yes
      register: process_list
      changed_when: false

    - name: Start "tmux" if needed
      command: tmux new-session -d
      when: "process_list.stdout.find('tmux') == -1"

    - name: Will start the tmux optimiser based on current ./session.mux
      command: bash ~/session.mux cryptopt
      async: 2592000               # 60*60*24*30 – 1 month
      poll: 0
