#!/usr/bin/env ansible-playbook
# vim: set tw=2 sw=2 sts=2:

- hosts: intel amd
# - hosts: kivsa nakhash aljamus nuc akrav akavish pil arnevet
  become: false
    # fail entire playbook, if any host fails (esp. the touch command)
  any_errors_fatal: true
  vars:
    suff: "results.bls12.wilson.20230418T135500"
    asmFolder:  "/mnt/pil/x-val.{{suff}}/asm"
    jsonFolder: "/mnt/pil/x-val.{{suff}}/json"
    resultDir: /home/joel/cryptopt/{{suff}}
    N: 10

  tasks:
    - name: create folders and set permissions
      become: true
      shell:
        cmd: if test "$(hostname)" = 'pil'; then mkdir  -p "{{asmFolder}}" "{{jsonFolder}}"; chown -R nobody "$(dirname "{{asmFolder}}")"; chmod -R 777 "$(dirname "{{asmFolder}}")"; echo "done";  else sleep 2; echo no; fi

    - name: MOUNT PIL
      become: true
      command: mount /mnt/pil

    - name: touch output file to check permissions
      command:
        cmd: touch "{{jsonFolder}}/{{inventory_hostname}}.json" && touch "{{asmFolder}}/{{inventory_hostname}}.touch"

      register: compare_status
      failed_when: compare_status.rc != 0

    - name: GATHER BEST ASMS
      command:
        chdir: ~/cryptopt/modules/scripts/misc
        cmd: bash archive-fast-asm.sh
      environment:
        RES: "{{resultDir}}"
        DEST: "{{asmFolder}}"

    - name: enable perf_counter
      become: true
      shell:
        cmd: echo "1" > /proc/sys/kernel/perf_event_paranoid

    - name: SET FREQ
      #dont use become, it'll change ~
      command:
        cmd: sudo ./set_frequency.sh fix {{low_freq}}
        chdir: ~/cryptopt/modules/scripts/misc
      ignore_errors: yes

    - name: RUN XVAL
      command:
        cmd: bash ./x-val.sh "{{asmFolder}}" "{{jsonFolder}}/{{inventory_hostname}}.json"
        chdir: ~/cryptopt/modules/scripts/misc
      register: compare_status
      failed_when: compare_status.rc != 0

    - name: RESET FREQ
      #dont use become, it'll change ~
      command:
        cmd: sudo ./set_frequency.sh default
        chdir: ~/cryptopt/modules/scripts/misc
      ignore_errors: yes
